### ISSUE TITLE
How can i see my oxsuite UI?

### ISSUE THREAD

**Issue by delvadianiraj07** [n-at/docker-ox-app-suite#2]
Hey There,

Actually, i have followed your steps and easily installed OX app suite. Thank you for the docker.
and then I have pasted my server IP address into the browser but couldn't see anything. I have not much knowledge of docker setup but I have heard that it need to mount the image.  What should I do so I can see UI in my browser.

I appreciate your quick help. Thank you in advance :)

Thanks,
Niraj

**Comment by n-at** [comment]
After you built the image (with tag ox for example), start it with command:

    docker run -itd -p 80:80 --name ox ox

Container needs some time to start. You can see startup logs with command:

    docker logs -f ox

When line like this will appear in log output:

    [....] Starting web server: apache2apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2 for ServerName

it means container finished startup. You can access OX by http://your_server_ip

**Comment by delvadianiraj07** [comment]
Yes, I used all the default configuration and ox tag works for me I can see the UI and I also logged into it. 
I appreciate your help.
